[package]
name = "axum-derive-otel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
axum-core = "0.4"
http = "1.1"
opentelemetry = "0.22"
opentelemetry_sdk = "0.22"
tracing = "0.1"
tracing-opentelemetry = "0.23"
